apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: book-app
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: jyotiraditya11/book-app-frontend:v1
        ports:
        - containerPort: 5173
